pipeline:
  build:
    image: node:6.10.2-alpine
    commands:
      - npm install
      - npm start &
      - npm i nightwatch -g
      - cd test && nightwatch

  notify:
    image: eisenxu/drone-ketsu-notification
    token: ${EXAM_ADMIN_TOKEN}
    host: https://ketsu-backend.herokuapp.com
    when:
      status: [ success, failure ]
      
services:
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
